### ISSUE TITLE
Add support to get tags from network files using -fast option

### ISSUE THREAD

**Issue by fcy** [janfri/mini_exiftool#15]
ExifTool supports a very awesome option to load Exif data from slow network connections without the need to download a big photo file. I'd like to implement support for this option in MiniExifTool.

This is the CLI to use the `-fast` option:

```
wget -qO - http://farm6.staticflickr.com/5015/5458914734_8fd3f33278_o.jpg | exiftool -fast -
```

My idea if to create an initializer that receives the URL to the file and pipes it to `exiftool -fast` and then uses the already existing `parse_output`. 

I've a few implementation questions:

1. wget is not available in every SO. Any ideas on how to do the "download pipe" using pure Ruby classes? Any other command that is more widely available?
2. I don't know the code base. Any tips on how to implement this?

What do you think?

**Comment by janfri** [comment]
I have implemented support for reading from IOs and by the way the -fast option. Maybe this would solve this issue if there is a solution to create a Ruby IO object for reading from network over HTTP. Please checkout release 2.6.0.

```ruby
io = ...
exif = MiniExiftool.new io, fast: true
```

**Comment by janfri** [comment]
@fcy MiniExiftool now supports es well as IO instances as the options fast and fast2.

```ruby
equire 'mini_exiftool'
require 'net/http'
require 'open3'

uri = URI('http://farm6.staticflickr.com/5015/5458914734_8fd3f33278_o.jpg')
output, input = IO.pipe

# Reading asynchron
Thread.new do
  Net::HTTP.start(uri.host, uri.port) do |http|
    request = Net::HTTP::Get.new uri
    http.request request do |response|
      response.read_body do |chunk|
        input.write chunk
      end
    end
  end
  io.close
end

exif = MiniExiftool.new output, fast2: true
puts exif.datetimeoriginal
```
