### ISSUE TITLE
Changing the EXIF metadata is not working for the same file

### ISSUE THREAD

**Issue by hiteshpatwari** [janfri/mini_exiftool#24]
I just updated some of the props of the image but it does not seem to work.

```
         inf = MiniExiftool.new(file.path)
        ap @a = inf.Make

        if inf.make
          print "-------- MAKE \n"
          inf.make = 'X'
          inf.Make = 'NA'
        end


        inf.save

        print "--0-=-=-=-=-=-=-=-= after \n"
        ap @b = inf
```

I don't see `Make ` as `X or NA`.

**Comment by janfri** [comment]
I don't fully understand what you are doing:

What is the value of the variable ```file```? What is the construct ```ap @a = ...```? (Never seen this in Ruby code before.)

The following works for me
```ruby
info = MiniExiftool.new('test.jpg')
puts info.make
info.make = 'X'
info.save

info2 = MiniExiftool.new('test.jpg')
puts info2.make
```

**Comment by hiteshpatwari** [comment]
IS there a way to make all Exif properties as 'X' except ImageSize, FileSize, ImageWidth,ImageHeight ?

**Comment by janfri** [comment]
GPSPosition is not writable direct by Exiftool, see
```ruby
MiniExiftool.writable_tags
```
to get a list of tags which are writable.

You can iterate over the tags of a file:
```ruby
info = MiniExiftool.new('test.jpg')
info.tags.each do |tag|
  next if %w[ImageSize FileSize ImageWidth ImageHeight].include? tag
  info[tag] = ''
end
info.save!
```
Hint: Use the method ```MiniExiftool.save!``` (with bang) to get an exception if the write of tags fails.

**Comment by janfri** [comment]
Do you need further help?

**Comment by hiteshpatwari** [comment]
Nope, the implementation is working.
