### ISSUE TITLE
Allow passing an IO to MiniExiftool.new

### ISSUE THREAD

**Issue by Gaelan** [janfri/mini_exiftool#25]
This should be pretty simple to implement (just pipe the IO into `exiftool -`). Support for the `-fast` option (see #15) could be a possible improvement, but isn't necessary.

**Comment by janfri** [comment]
How about a pull request id it's so simple. ;-)

**Comment by Gaelan** [comment]
I'll try to get one done tonight. No promises.

**Comment by janfri** [comment]
It seems to need a little more to do, especially to handle the case to have no filename. I have already adapted the master to use Open3 instead of direct calls via backticks, so it is easier to support IOs. I will have a look at it in the next week.

**Comment by janfri** [comment]
So I have implemented support for reading from IOs and by the way the -fast option. Please checkout release 2.6.0.

**Comment by janfri** [comment]
@Gaelan Could you give me an example of your use case? Maybe one we can add to the examples of mini_exiftool?

**Comment by Gaelan** [comment]
@janfri I was thinking of Exiftooling a file that was already saved to S3. Another simple use case would be getting metadata from a URL.

**Comment by janfri** [comment]
How do you get a non-blocking IO-object? If I use open-uri for example the whole file will be downloaded before I can read from the IO, so the fast option doesn't make any sense here. :-(

**Comment by Gaelan** [comment]
@janfri I found [this]:

```ruby
uri = URI('http://example.com/large_file')

Net::HTTP.start(uri.host, uri.port) do |http|
  request = Net::HTTP::Get.new uri

  http.request request do |response|
    open 'large_file', 'w' do |io|
      response.read_body do |chunk|
        io.write chunk
      end
    end
  end
end
```

It's "a bit" more verbose than open-uri, but perhaps you could adapt this to run on a separate thread and write into an IO which you then passed to EXIFtool. Surely there's a better way, right? I'll keep looking.

[this]: http://ruby-doc.org/stdlib-2.1.5/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Streaming+Response+Bodies

**Comment by janfri** [comment]
@Gaelan Thanks a lot. I've added both to the new example how_speedup_with_fast_option.

**Comment by Gaelan** [comment]
@janfri Thanks for implementing this so quickly! I'll add it to my app soon.
