### ISSUE TITLE
Writing multiple tags in one `run`

### ISSUE THREAD

**Issue by passcod** [janfri/mini_exiftool#30]
If I'm reading the code correctly, this tool calls exiftool once per tag it needs to write. The [documentation says](http://www.sno.phy.queensu.ca/~phil/exiftool/mistakes.html#M4) that it is possible to write multiple tags in one invocation. Could this be used?

**Comment by janfri** [comment]
Not with mini_exiftool, have a look at [multi_exiftool](https://github.com/janfri/multi_exiftool).

**Comment by janfri** [comment]
Not with mini_exiftool. Have a look at [multi_exiftool](https://github.com/janfri/multi_exiftool).
