### ISSUE TITLE
Extract Group Data

### ISSUE THREAD

**Issue by btrewern** [janfri/mini_exiftool#31]
Is there any way to extract the Exif Group data?  I've looked through the code and can't see anywhere that the -G0 or -G1 options are used.

If this is not available then is this the best forum to raise a feature request?

**Comment by janfri** [comment]
EXIF group data isn't supported. Have a look at [multi_exiftool](https://github.com/janfri/multi_exiftool), there is group support.
I hope this helps. If not let me know.

**Comment by btrewern** [comment]
Thanks for that I'll look into it.

**Comment by janfri** [comment]
@btrewern I hope you have found what you need. I close this issue. Feel free to reopen it if necessary.
