### ISSUE TITLE
Define respond_to_missing?

### ISSUE THREAD

**Issue by nerixim** [janfri/mini_exiftool#37]
Hi, thanks for your work!

I tried to use `Forwardable` to wrap calls to `MiniExiftool` instance for my project, but I got warning regarding forwarding to private methods.
Seems like it should be solved by defining `respond_to_missing?`. https://bugs.ruby-lang.org/issues/13326
IMO defining the `respond_to_missing?` method is generally a good idea.

**Comment by janfri** [comment]
I will have a look t it.

**Comment by janfri** [comment]
I have just released mini_exiftool 2.10.0. There is ```MiniExiftool#respond_to_missing?``` implemented. I hope it works for you now.

**Comment by janfri** [comment]
I will close this issue now. Feel free to reopen it if your problem isn't solved.
