### ISSUE TITLE
US postal codes are parsed to integers instead of strings

### ISSUE THREAD

**Issue by jvradelis** [janfri/mini_exiftool#40]
US postal codes beginning with a 0 and containing another zero are converted to integers and drop the initial 0.

For example, a postal code like '02109' (Boston MA) will become 2109.  

I believe that line 464 of mini_exiftool.rb (convert_after_load) is intended to preserve postal codes as strings, but the match condition (when /^0+[1-9]+$/) does not handle this example properly because the second zero causes the match to fail.  I propose that the condition be changed to:  when /^0+[0-9]+$/.

**Comment by janfri** [comment]
Good catch. Thank you.

Bug is fixed in mini_exiftool 2.10.1.

**Comment by jvradelis** [comment]
Indeed, it is.  Thanks very much.
