### ISSUE TITLE
IPTC Data types, "seem" to work but don't get persisted.

### ISSUE THREAD

**Issue by Jaciones** [janfri/mini_exiftool#41]
MiniExifTool seems to validate proper IPTC data structure, and then accepts ONLY the properly formatted structure, but then never persists the validated structure. Here is an example where 'sample.jpg" can be ANY ".jpg" file.

```
photo = MiniExiftool.new 'sample.jpg'
photo["CopyrightOwner"] = "jason"
 => "jason"
photo.save
photo.errors
 => {"copyrightowner"=>"Warning: Improperly formed structure for XMP-plus:CopyrightOwner"}
```

So far, this is absolutely correct. As per the IPTC spec, CopyrightOwner requires 2 children nodes, "CopyrightOwnerID" && "CopyrightOwnerID".

So if we add those:
```
photo["CopyrightOwner"]='{"CopyrightOwnerID" : "23412412","CopyrightOwnerName" : "jason"}}'
photo.save
 => true
```

But the NEITHER the output file, nor the existing photo object have those values saved:
```
photo["CopyrightOwner"]
 => ""
```

NOR

```
exiftool sample.jpg | grep "Copyright Owner"
Copyright Owner        :     
``` 

**Expected Result: "Copyright Owner" would be persisted in the EXIF data as per IPTC spec.**

**Comment by janfri** [comment]
It's much simpler ;-)
```ruby
photo = MiniExiftool.new 'sample.jpg'
photo.copyright_owner_name = 'jason'
photo.copyright_owner_id = '23412412'
photo.save
```

**Comment by janfri** [comment]
@Jaciones let me know if you need further help.
