### ISSUE TITLE
# Version 2.1, February 1999

### ISSUE THREAD

**Issue by MtnBiker** [janfri/mini_exiftool#42]
The date had me concerned. I think it's wrong. Trivial.

Line 13 in the the main file.

Thanks for this great gem.

I got here because I'm having an issue, but's it's probably how I'm doing it.

**Comment by janfri** [comment]
This is the version of the LGPL (not of mini_exiftool):
```
# Licensed under the GNU LESSER GENERAL PUBLIC LICENSE,
# Version 2.1, February 1999
```
see also file https://github.com/janfri/mini_exiftool/blob/master/COPYING and https://www.gnu.org/licenses/old-licenses/lgpl-2.1
