### ISSUE TITLE
"require 'rational' " causes load error(cannot load such file -- rational) for ruby 2.7.8

### ISSUE THREAD

**Issue by tomwang57** [janfri/mini_exiftool#47]
ruby version: 2.7.8
bundler version: 2.3.3

```
.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mini_exiftool-2.10.2/lib/mini_exiftool.rb:20:in `require': cannot load such file -- rational (LoadError)
```

It seems that `require 'rational'` is no longer needed to use Rational.

**Comment by janfri** [comment]
On my system with Ruby 3.0.6 it causes no error:
```ruby
>> RUBY_VERSION
=> "3.0.6"
>> require 'rational'
=> false
>> 
```

**Comment by janfri** [comment]
Does the following work in irb for you?
```ruby
Rational(1, 2)
```

**Comment by tomwang57** [comment]
> Does the following work in irb for you?
> 
> ```ruby
> Rational(1, 2)
> ```

Yes, this works

**Comment by tomwang57** [comment]
> On my system with Ruby 3.0.6 it causes no error:
> 
> ```ruby
> >> RUBY_VERSION
> => "3.0.6"
> >> require 'rational'
> => false
> >> 
> ```

It is used in a Rails project with Gemfile like:

```
...
gem 'mini_exiftool_vendored'
...
```

And running `bundle install` caused the error.

**Comment by tomwang57** [comment]
Add the following line before `Bundler.require(*Rails.groups)` fixes the error:

```ruby
# fix: cannot load such file -- rational
require 'mini_exiftool_vendored'
```

Don't know why.
