### ISSUE TITLE
#filename_or_io() duck typing fails for instances of Pathname

### ISSUE THREAD

**Issue by rlue** [janfri/mini_exiftool#50]
### What's happening

```ruby
MiniExiftool.new(Pathname.new('/path/to/file')).save!
/.../lib/mini_exiftool.rb:216:in `save': No writing support when using an IO. (MiniExiftool::Error)
```

### What I expect

no error, successful save

### Why it's failing

`MiniExiftool#load()` guesses whether its argument is a filename or an io based on whether it responds to `#to_str?` or `#read` ([source](https://github.com/janfri/mini_exiftool/blob/ce3fa4716e2dc89d32f73ad6332033266284cac3/lib/mini_exiftool.rb#L135)). Pathnames do not respond to `#to_str` but are easily converted to strings, and should naturally be treated as filenames. 

### Proposed solution

I don't have an elegant fix for this, but I think a better approach might be

```ruby
if filename_or_io.is_a?(IO)
  # ...
else
  # use filename_or_io.to_s here
end
```

since the filename logic already contains some reasonable filters for invalid input.

**Comment by janfri** [comment]
It's hopefully fixed in mini_exiftool 2.13.0. Please let me know if it works for you.

**Comment by rlue** [comment]
Unfortunately, it was not—[`Pathname#read()` is a thing](https://rubyapi.org/3.3/o/pathname#method-i-read) :\\

**Comment by janfri** [comment]
Ok, than it's not as easy to solve as I thought. At the moment you have to use
```ruby
MiniExiftool.new(Pathname.new('/path/to/file').to_s).save!
```

**Comment by janfri** [comment]
After a while of thinking, I decided to handle Pathname explicitly. Please try mini_exiftool 2.13.1.

**Comment by rlue** [comment]
fabulous! thanks for the very speedy response, and happy holidays

**Comment by janfri** [comment]
Great. Thank you for your analyse and also happy holidays.
